up v0.1.5

diff --git a/.github/workflows/release-docs.yaml b/.github/workflows/release-docs.yaml
--- a/.github/workflows/release-docs.yaml
+++ b/.github/workflows/release-docs.yaml
@@ -88,7 +88,7 @@ jobs:
 
         if [ "$versions_count" -gt "${{ env.MAX_COMMIT_PER_BRANCH_DEPLOYED }}" ]; then
             echo "Removing oldest version: $oldest_version"
-            aws s3 rm --recursive s3://${{ env.BUCKET_NAME }}/$escaped_branch_name/$oldest_version || echo "Error removing version"
+            aws s3 rm --recursive s3://${{ env.BUCKET_NAME_LAB }}/$escaped_branch_name/$oldest_version || echo "Error removing version"
         else
             echo "No need to remove versions."
         fi
@@ -134,7 +134,7 @@ jobs:
 
         if [ "$versions_count" -gt "${{ env.MAX_PRO_VERSIONS }}" ]; then
             echo "Removing oldest version: $oldest_version"
-            aws s3 rm --recursive s3://${{ secrets.BUCKET_NAME }}/$oldest_version/ || echo "Error removing version"
+            aws s3 rm --recursive s3://${{ secrets.BUCKET_NAME }}/$oldest_version || echo "Error removing version"
         else
             echo "No need to remove versions."
         fi
