update action

diff --git a/.github/workflows/release-docs.yaml b/.github/workflows/release-docs.yaml
--- a/.github/workflows/release-docs.yaml
+++ b/.github/workflows/release-docs.yaml
@@ -14,6 +14,7 @@ env:
   AWS_REGION_LAB: "us-east-1"
   MAX_BRANCH_DEPLOYED: 5
   MAX_COMMIT_PER_BRANCH_DEPLOYED: 3
+  MAX_PRO_VERSIONS: 3
 
 permissions:
       id-token: write
@@ -71,7 +72,7 @@ jobs:
         [ "$lines_count" -gt "${{ env.MAX_BRANCH_DEPLOYED }}" ] && aws s3 rm --recursive s3://${{ secrets.BUCKET_NAME_LAB }}/$last_branch/
 
         echo "Cleanup commit folders"
-        aws s3 ls s3://pandas-challenge-github-action-test-bucket/$escaped_branch_name/ | awk '$NF ~ /\/$/ { print $NF }' > .commit_versions
+        aws s3 ls s3://${{ secrets.BUCKET_NAME_LAB }}/$escaped_branch_name/ | awk '$NF ~ /\/$/ { print $NF }' > .commit_versions
         cat .commit_versions  # Debug: print the versions
 
         oldest_version=$(head -1 .commit_versions)
@@ -106,9 +107,28 @@ jobs:
         role-session-name: samplerolesession
         aws-region: ${{ env.AWS_REGION }}
     - name:  Copy to PRO S3
-      if: ${{ github.ref == 'refs/heads/master' && env.THIS_VERSION_COMPARABLE > env.LATEST_VERSION_COMPARABLE }}
+#      if: ${{ github.ref == 'refs/heads/master' && env.THIS_VERSION_COMPARABLE > env.LATEST_VERSION_COMPARABLE }}
       run: |
-        aws s3 sync ./site/ s3://${{ secrets.BUCKET_NAME }}/
+        version=$(cat version)
+        date_prefix=$(date +%Y-%m-%d-%H-%M-%S_)
+        aws s3 sync ./site/ s3://${{ secrets.BUCKET_NAME }}/$date_prefix$version
+        aws s3 sync ./site/ s3://${{ secrets.BUCKET_NAME }}/latest
+
+        echo "Cleanup OLD PRO version folders"
+        aws s3 ls s3://${{ secrets.BUCKET_NAME }}/ | awk '$NF ~ /\/$/ { print $NF }' | sed -E s/^latest$//g | grep -Ev "^$" > .pro_versions
+        cat .pro_versions  # Debug: print the versions
+
+        oldest_version=$(head -1 .pro_versions)
+        versions_count=$(cat .pro_versions | wc -l)
+        echo "Oldest version: $oldest_version"
+        echo "Versions count: $versions_count"
+
+        if [ "$versions_count" -gt "${{ env.MAX_PRO_VERSIONS }}" ]; then
+            echo "Removing oldest version: $oldest_version"
+            aws s3 rm --recursive s3://${{ secrets.BUCKET_NAME }}/$oldest_version || echo "Error removing version"
+        else
+            echo "No need to remove versions."
+        fi
     - name: Invalidate PRO CloudFront cache
       if: ${{ github.ref == 'refs/heads/master' && env.THIS_VERSION_COMPARABLE > env.LATEST_VERSION_COMPARABLE }}
       run: |
